DROP SCHEMA IF EXISTS `marciadb`;
CREATE SCHEMA `marciadb`;
USE `marciadb`;

CREATE TABLE CUSTOMER (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(45) NOT NULL,
    LastName VARCHAR(45) NOT NULL,
    Phone VARCHAR(45) NOT NULL,
    Email VARCHAR(255),
    Address VARCHAR(255),
    HasMembership BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE ORDER_INFO (
    OrderID INT PRIMARY KEY AUTO_INCREMENT,
    DropDate DATE,
    PromiseDate DATE,
    PickupDate DATE,
    MethodOfPayment VARCHAR(45),
    CUSTOMER_CustomerID INT NOT NULL,
    FOREIGN KEY (CUSTOMER_CustomerID) REFERENCES CUSTOMER(CustomerID) ON UPDATE RESTRICT
);

CREATE TABLE SERVICE (
    ServiceID INT PRIMARY KEY AUTO_INCREMENT,
    Description VARCHAR(255),
    Price DECIMAL(10, 2),
    HoursRequired INT
);

CREATE TABLE ORDER_HAS_SERVICE (
    ORDER_INFO_OrderId INT,
    SERVICE_ServiceID INT,
    PRIMARY KEY (ORDER_INFO_OrderID, SERVICE_ServiceID)
);
